{% set name = "pytorch-lightning" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PyTorchLightning/pytorch-lightning/archive/{{ version }}.tar.gz
  sha256: c623ffdf26096b0e7cf0b6f07e95b6333a193bb215cf5bd7d67f1a698d94f296 

build:
  number: 1 
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip {{ pip }}
    - python 
  run:
    - future {{ future }} 
    - packaging
    - numpy {{ numpy }} 
    - python
    - pyyaml {{ pyyaml }}
    - tensorboard {{ tensorboard }} 
    - pytorch-base {{ pytorch }} 
    - torchvision-base {{ torchvision }}
    - tqdm  {{ tqdm }}
    - fsspec {{ fsspec }}

test:
  imports:
    - pytorch_lightning

about:
  home: https://pypi.org/project/pytorch-lightning/
  summary: PyTorch Lightning is the lightweight PyTorch wrapper for ML researchers. Scale your models. Write less boilerplate.
  description: PyTorch Lightning is the lightweight PyTorch wrapper for ML researchers. Scale your models. Write less boilerplate.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
