{% set name = "lightning-cloud" %}
{% set version = "0.5.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lightning_cloud-{{ version }}.tar.gz
  sha256: d8bfd825403686d686788d19f77495400e25d0d925667cf086a647eacb5ac8f5

build:
  number: 1
  noarch: python
  string: pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed . -vv

requirements:
  host:
    - pip {{ pip }}
    - python 
  run:
    - python
    - click
    - requests
    - rich
    - pyjwt
    - fastapi
    - six
    - websocket-client

test:
  imports:
    - lightning_cloud
  commands:
    - pip check

about:
  home: https://pypi.org/project/pytorch-lightning/
  summary: PyTorch Lightning is the lightweight PyTorch wrapper for ML researchers. Scale your models. Write less boilerplate.
  description: PyTorch Lightning is the lightweight PyTorch wrapper for ML researchers. Scale your models. Write less boilerplate.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
