{% set name = "lightning-utilities" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9e31617eccbbadc6b737a2432fd7076ff8e24957f9c63aeba2530b189e19319c

build:
  number: 3
  noarch: python
  string: pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip {{ pip }}
    - python 
  run:
    - python
    - fire
    - packaging
    - typing_extensions >=4.0,<5
    - setuptools >=78.1.1  #[x86]
    - setuptools           #[not x86]
test:
  requires:
    - typing_extensions >=4.0,<5
    - setuptools >=78.1.1  #[x86]
    - setuptools           #[not x86]
  imports:
    - lightning_utilities
  commands:
    - pip check

about:
  home: https://github.com/Lightning-AI/utilities
  summary: Lightning Utilities.
  description: Lightning Utilities.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
