{% set name = "lightning-fabric" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/Lightning-AI/lightning
  git_rev: {{ version }}

build:
  number: 1
  noarch: python
  string: pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  script: export PACKAGE_NAME=fabric; {{ PYTHON }} -m pip install . --no-deps --ignore-installed . -vv

requirements:
  build:
    - git-lfs
  host:
    - pip {{ pip }}
    - python 
  run:
    - lightning-utilities
    - pytorch-base {{ pytorch }}
    - packaging
    - fsspec
    - numpy {{ numpy }}
    - typing_extensions {{ typing_extensions }}
     
test:
  imports:
    - lightning_fabric 
#  commands:
#    - pip check

about:
  home: https://github.com/Lightning-AI/lightning
  summary: Use Lightning Apps to build everything from production-ready, multi-cloud ML systems to simple research demos.
  description: Use Lightning Apps to build everything from production-ready, multi-cloud ML systems to simple research demos.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
