{% set name = "pytorch-lightning" %}
{% set version = "2.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/Lightning-AI/lightning
  git_rev: {{ version }}

build:
  number: 1
  noarch: python
  string: pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  script: export PACKAGE_NAME=pytorch; {{ PYTHON }} -m pip install . --no-deps --ignore-installed . -vv

requirements:
  build:
    - git-lfs
  host:
    - pip {{ pip }}
    - python 
  run:
    - packaging
    - numpy {{ numpy }} 
    - python
    - pyyaml {{ pyyaml }}
#    - tensorboard {{ tensorboard }}
    - tensorboardX
    - pytorch-base {{ pytorch }} 
    - torchvision-base {{ torchvision }}
    - tqdm  {{ tqdm }}
    - fsspec {{ fsspec }}
    - torchmetrics {{ torchmetrics }}
    - lightning-utilities

test:
  imports:
    - pytorch_lightning
  commands:                               # [build_type == 'cpu' or cudatoolkit == '11.8']
    - pip check                           # [build_type == 'cpu' or cudatoolkit == '11.8']

about:
  home: https://pypi.org/project/pytorch-lightning/
  summary: PyTorch Lightning is the lightweight PyTorch wrapper for ML researchers. Scale your models. Write less boilerplate.
  description: PyTorch Lightning is the lightweight PyTorch wrapper for ML researchers. Scale your models. Write less boilerplate.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
