{% set name = "lightning" %}
{% set version = "1.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/Lightning-AI/lightning
  git_rev: {{ version }}

build:
  number: 1
  noarch: python
  string: pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed . -vv

requirements:
  build:
    - git-lfs
  host:
    - pip {{ pip }}
    - python 
  run:
    - future {{ future }} 
    - packaging
    - numpy {{ numpy }} 
    - python
    - pyyaml {{ pyyaml }}
    - tensorboard {{ tensorboard }} 
    - pytorch-base {{ pytorch }} 
    - torchvision-base {{ torchvision }}
    - tqdm  {{ tqdm }}
    - fsspec {{ fsspec }}
    - torchmetrics {{ torchmetrics }}
    - pyDeprecate 0.3.2
    - lightning-utilities

test:
  imports:
    - lightning
  commands:
    - pip check

about:
  home: https://github.com/Lightning-AI/lightning
  summary: PyTorch Lightning is the lightweight PyTorch wrapper for ML researchers. Scale your models. Write less boilerplate.
  description: PyTorch Lightning is the lightweight PyTorch wrapper for ML researchers. Scale your models. Write less boilerplate.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
