{% set name = "lightning-app" %}
{% set version = "1.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Lightning-AI/lightning/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 990f9af72cbc79c0f1536486b1abf86aca7dfccbd330ba718f9af61e2c837756

build:
  number: 1
  noarch: python
  string: pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed . -vv

requirements:
  host:
    - pip {{ pip }}
    - python 
  run:
    - packaging
    - python
    - lightning
    - lightning-utilities
    - lightning-cloud
    - lightning-api-access
    - deepdiff
    - croniter
    - fastapi 
    - websockets
    - click
    - requests
    - rich
    - fsspec {{ fsspec }}
    - uvicorn
    - six
    - websocket-client
    - beautifulsoup4
    - starsessions
    - s3fs
    - arrow 
    - traitlets
    - psutil
    - inquirer

test:
  imports:
    - lightning_app 
#  commands:
#    - pip check

about:
  home: https://pypi.org/project/pytorch-lightning/
  summary: PyTorch Lightning is the lightweight PyTorch wrapper for ML researchers. Scale your models. Write less boilerplate.
  description: PyTorch Lightning is the lightweight PyTorch wrapper for ML researchers. Scale your models. Write less boilerplate.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
