{% set name = "torchmetrics" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/PyTorchLightning/metrics
  git_rev: v{{ version }}

build:
  noarch: python
  number: 2 
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - packaging
    - setuptools >=78.1.1    #[x86]
    - setuptools             #[not x86]
    - python 
    - pytorch-base {{ pytorch }}
    - tqdm {{ tqdm }}
    - lightning-utilities =0.10.0

test:
  imports:
    - torchmetrics

about:
  home: https://pypi.org/project/torchmetrics/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Machine learning metrics for distributed, scalable PyTorch applications.
  description: |
    Machine learning metrics for distributed, scalable PyTorch applications.
  doc_url: https://torchmetrics.readthedocs.io/
  dev_url: https://github.com/PyTorchLightning/metrics

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
